name: CI and CD on GitHub Actions  

on: 
  schedule:  
    - cron: '29 9 * * 1,3' # Every Monday and Wednesday, at 9h29 
                           # GitHub is scared of ghosts! 
  push: 
    branches: 
      - main 

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9 
      uses: actions/setup-python@v2
      with:
        python-version: 3.9 
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda env update --file env.yml --name base 
        make install 
        make config 
        make models 
        make data 
    - name: Check models 
      run: |
        cd tests 
        python test_default.py 
        python test_craft.py 
